### PR TITLE
feature: Composite Unit Definitions

### PR DESCRIPTION
**Pull request by CrownedPhoenix**
Adds functionality for defining custom units in terms of existing units.

### CODE REVIEW

**Comment by CrownedPhoenix** [comment]
Happy to add more tests. Not entirely confident I've covered all the interesting cases in spite of the coverage.

**Comment by CrownedPhoenix** [comment]
Actually I think I got a problem with the fact that I don't use the coefficients or constants of any of the constituent components. :'(

**Comment by NeedleInAJayStack** [comment]
I have been considering moving away from the global unit registry singleton to an instance approach. Would that help this effort?

**Comment by NeedleInAJayStack** [comment]
@CrownedPhoenix You know, after looking at it, I think you may be able to accomplish what you're trying to do with a simple assignment to a combined unit. Here's your test rewritten with the approach I'm talking about:

```swift
    func testCompositeUnitDefine() throws {
        let ampereHour = Unit.ampere * .hour

        // Test conversion from custom unit
        XCTAssertEqual(
            try 1.measured(in: ampereHour).convert(to: .coulomb),
            3600.measured(in: .coulomb),
            accuracy: accuracy
        )

        // Test conversion to custom unit
        XCTAssertEqual(
            try 3600.measured(in: .coulomb).convert(to: ampereHour),
            1.measured(in: ampereHour),
            accuracy: accuracy
        )

        let ampereSquareMeters = Unit.ampere * .meter.pow(2)
        let joulePerTesla = Unit.joule / .tesla

        // Test conversion from custom unit
        XCTAssertEqual(
            try 1.measured(in: ampereSquareMeters).convert(to: joulePerTesla),
            1.measured(in: joulePerTesla),
            accuracy: accuracy
        )

        // Test conversion to custom unit
        XCTAssertEqual(
            try 1.measured(in: joulePerTesla).convert(to: ampereSquareMeters),
            1.measured(in: ampereSquareMeters),
            accuracy: accuracy
        )
    }
```

**Comment by CrownedPhoenix** [comment]
Yeah you are right. I came to that same conclusion.
I'm gonna close this PR.

I have found some work related to this compositional stuff that I think I'm gonna look into.

One current limitation I'm running into with the operator combinations (i.e. `.meter / .second` etc) is that there is no way to modify coefficients. 

For example, it seems like it should be possible to reduce all of the pre-defined units to simply be their SI base units for each  quantity dimension (meter, kilogram, second, etc) and then define all the scales of those units as expressions rather than using the `DefinedUnit` initializer.
Specifically:
```swift
static let meter = Unit(definedBy: DefaultUnits.meter)
static let centimeter = 0.01 * .meter
static let kilometer = 1000 * .meter
```

This would improve the extensibility of the unit types in a way that downstream consumers can do without having to make a PR.

A second thought I had while playing around with stuff was that rather than the `UnitType` enum (none, defined, composite) and the `composedOf` Unit init, we could hoist the data storage format of `[Quantity: Int]` directly into the unit and then do the dictionary merging directly on the Unit itself.

This would further support the ability to define new units in terms of old units using just the arithmetic operators.


And finally, I think there would be some benefit to defining a separate NonLinearUnit type at the top level that would prevent people from attempting to combine non-linear units in bad ways at compile time.

**Comment by CrownedPhoenix** [comment]
And regarding the removal of the Registry. It seems like the only purpose of the registry is for parsing units from strings.
I think it might make sense to remove the global definitions and just make the registry accept a symbol to Unit mapping that it uses in order to parse. That would allow you to remove an error case from the `DefinedUnit` where the specified symbol has disallowed characters because `DefinedUnit` would no longer store the symbol.

Furthermore, this would allow for multiple symbols for the same unit.

**Comment by CrownedPhoenix** [comment]
I'm just spamming this MR with all my thoughts, I'm sorry.

If we reworked the `[Quantity: Int]` to instead be something like `[BaseUnit: Int]` then we have a way to help remind the user that any new unit they define must be in terms of the base unit. I think right now it's possible to define two units in such a way that they are derived from different bases - but all this functionality is internal so maintainers shoulder the responsibility of making sure that all default units are defined in terms of the same base type for any given dimension.

I think that making `[Quantity: Int]` actually be required to be in whatever our common base units are (presumably SI) will help keep this consistent.

**Comment by NeedleInAJayStack** [comment]
No worries, happy to discuss it here!

Off the bat, I will say that there's definitely tension in this package between defining units in the type system (which would make free-form computed units like m/s difficult / impossible) and defining units as instances (which allows multiple 'meter' definitions, for example). We kinda end up wanting mixed behavior - run-time computation, but type-style referencing. Instances offer more flexibility at the risk of abuse.

> One current limitation I'm running into with the operator combinations (i.e. .meter / .second etc) is that there is no way to modify coefficients

I'm not sure why you'd want to change a coefficient in this case. The coefficient should become the combination of the sub-unit coefficients. Do you have an example?

> static let centimeter = 0.01 * .meter

In this case we aren't defining the name or symbol of centimeter. Were you just thinking that the SI prefixes (like `centi`) could be abstracted? If so, I agree, although we'd want to be sure to limit application to only SI units (no-one is using `kilofeet`). Since we'd limit it to only the SI units, which are a pretty fixed set, I'd probably lean toward just enumerating them in the default units instead of an abstraction.

> And finally, I think there would be some benefit to defining a separate NonLinearUnit type at the top level that would prevent people from attempting to combine non-linear units in bad ways at compile time.

That sounds interesting!

> I think it might make sense to remove the global definitions and just make the registry accept a symbol to Unit mapping that it uses in order to parse

That's an interesting idea. To make it work, we'd probably have to offload all Unit serialization onto UnitRegistry, since `Unit.symbol` is also used for encoding and string representations. I'd be open to ideas, although I'd say that this package generally takes the position that every defined unit should be 1) composable with other units and 2) able to be converted into string symbols and back, so I'd be a little hesitant splitting that up into separately managed mechanisms.

> If we reworked the [Quantity: Int] to instead be something like [BaseUnit: Int] then we have a way to help remind the user that any new unit they define must be in terms of the base unit

This is a good point - I can see how that would be confusing, especially since base units are implicit even though they follow the SI conventions. I'd maybe offer an alternative - that we have a `Quantity.baseUnit` function that will return the defined base unit of each quantity. That might make it more explicit. Also, my hope is that the compositional nature of this package means that clients aren't defining many custom units in the first place.

Finally, I'll just say that I'm having a bit of trouble gleaning the use cases from our conversation so if there are specific problems you're struggling to solve, just comment here or create an issue and I'd be happy to lend my insight (and add new docs in the process!)

**Comment by CrownedPhoenix** [comment]
## Type System Tension



> Off the bat, I will say that there's definitely tension in this package between defining units in the type system (which would make free-form computed units like m/s difficult / impossible) and defining units as instances (which allows multiple 'meter' definitions, for example). We kinda end up wanting mixed behavior - run-time computation, but type-style referencing. Instances offer more flexibility at the risk of abuse.

Yeah I've come around on this after my hacking around. Nothing more to say on this but I settled with having a single type.



## Coefficients Multiplication


> One current limitation I'm running into with the operator combinations (i.e. .meter / .second etc) is that there is no way to modify coefficients

> I'm not sure why you'd want to change a coefficient in this case. The coefficient should become the combination of the sub-unit coefficients. Do you have an example?

Yeah so here this syntax **multiplies** the `.meter` coefficient (which is 1) to create a new `Unit` struct with coefficient `a*b`.
The use here is then you can do:

```swift
static let centimeter = 0.01 * .meter
static let millimeter = 0.01 * .centimeter
static let nanometer = 0.01 * .millimeter

// Or more interesting
static let standardGravity = (9.80665 * .meter) / .second.pow(2)
```

Just makes it a bit easier to define new units in terms of other units.



## Not Defining Symbols

> static let centimeter = 0.01 * .meter

> In this case we aren't defining the name or symbol of centimeter. Were you just thinking that the SI prefixes (like centi) could be abstracted? If so, I agree, although we'd want to be sure to limit application to only SI units (no-one is using kilofeet). Since we'd limit it to only the SI units, which are a pretty fixed set, I'd probably lean toward just enumerating them in the default units instead of an abstraction.

Going down this road I definitely had to go against the position you mentioned that `every defined unit should be ... able to be converted into string symbols and back`.
I chose do do this because:
- Makes it much easier to define new units.
- I convinced myself that serialization was a separate problem. Moreover, a single unit might have multiple valid symbols that it can deserialize from. And since I already had in my head the idea that the UnitRegistry would instead just accept a mapping between units and their symbols. With that in mind, specifying the symbol for a unit at the definition site became uneccessary.

## Base Unit Specification
> If we reworked the [Quantity: Int] to instead be something like [BaseUnit: Int] then we have a way to help remind the user that any new unit they define must be in terms of the base unit

> This is a good point - I can see how that would be confusing, especially since base units are implicit even though they follow the SI conventions. I'd maybe offer an alternative - that we have a Quantity.baseUnit function that will return the defined base unit of each quantity. That might make it more explicit. Also, my hope is that the compositional nature of this package means that clients aren't defining many custom units in the first place.

I considered `Quantity.baseUnit` as well and my only concern with it was that it isn't immediately clear what the base units are when I'm defining a new unit. So I could mistakenly assume that it's something else if I don't dig inside the package. If all the names of the Quantities were their actual SI base measurement then I would have a shorter feedback loop that informs me the new unit I'm trying to define is incorrect.

For example, the following definition from the test assumes that the User knows that `Length` is really just `meter`.
Using the general term for the dimension makes it seem like `Length` could plausibly be any length measurement and so as the user I'd either:
- mistakenly assume that it's imperial (which would the coefficient needed)
- dig around in the package and make sure I remember what all the base units are

```swift
 let centifoot = try Unit.define(
    name: "centifoot",
    symbol: "cft",
    dimension: [.Length: 1],
    coefficient: 0.003048
)
```

It's worth saying that it's not terribly onerous to make sure I know what the base units are before trying to call `Unit.define` but it does seem like it's just unnecessary extra work for the user as opposed to just having intellisense give them this:

```swift
let centifoot = try Unit.define(
    name: "centifoot",
    symbol: "cft",
    dimension: [.meter: 1],
    coefficient: 0.003048
)
```

or even simpler:
```swift
let centifoot = 0.003048 * .meter
```


## Custom Units
> Also, my hope is that the compositional nature of this package means that clients aren't defining many custom units in the first place.

This goal I think could be furthered by enabling that `static func *(_ coefficient: Double, _ unit: Unit) -> Unit` function mentioned earlier. It seems that is a piece missing from the unit composability.


## Conclusion
> Finally, I'll just say that I'm having a bit of trouble gleaning the use cases from our conversation so if there are specific problems you're struggling to solve, just comment here or create an issue and I'd be happy to lend my insight (and add new docs in the process!)

Yeah sorry this was my first worry with all my thought vomiting.

The main use cases I have that caused me to get into all this in the first place are:
1. Defining new units in terms of other units. Specifically I had cases where I needed to add a coefficient. For example, defining `gigajoule` in terms of `joule`. Currently the way is to call `Unit.define` and then go copy the definition of `joule` and change the coefficient. I was wanting to just do `1000 * kilojoule`.

2. Defining custom dimensions. The base SI dimensions are insufficient for everything. For example, I think the test including:
```
let apple = try Unit.define(
    name: "apple",
    symbol: "apple",
    dimension: [.Amount: 1],
    coefficient: 1
)

let carton = try Unit.define(
    name: "carton",
    symbol: "carton",
    dimension: [.Amount: 1],
    coefficient: 48
)
```
Is problematic because `apple` and `mole` would be dimensionally equivalent - which is incorrect. Even though they measure an "amount" of something, moles and apples are not comparable. You need to have a conversion from apples to moles in order to get `mole/apple`.
One of the changes hacked around with enabled:
```
let apple = Unit.define(dimension: "apple")

let carton = 48 * apple
```

I ran into this problem a bunch in practical use cases as well for units like: CoefficientOfPerformance, CyclesPerHour, decibel etc
Making these all unitless is equivalently incorrect because they are still not dimensionally equivalent.
These are technically all their own custom dimension and if I tried to convert `5.0 coefficient of performance` to `decibel` I should get an error.

**Pull request closed without merging**
